### ISSUE TITLE
Start project FizzBuzz

### ISSUE THREAD

**Issue by charlesemery15** [charlesemery15/FizzBuzz-in-javaScript#1]
- Create file structure

- Download latest zip file from [jasmine](https://github.com/jasmine/jasmine/releases)

- Copy to the project

- cp -r ~/Downloads/jasmine-standalone-2.3.4.zip .
unzip jasmine-standalone-2.3.4.zip

**Comment by joepike-zz** [comment]
Downloaded jasmine v2.9.1 and unzipped in parent directory of project folder. Lib, spec, src folders and SpecRunner.html file automatically generated. Project now set up for testing.
